"""Tests for the `pkgskills` host declaration and the commands it mounts."""

from __future__ import annotations

from importlib import resources
from pathlib import Path

import pytest
from pkgskills import render_prompt, split_frontmatter
from pkgskills.testing import (
    Sandbox,
    assert_prompt_commands,
    assert_spec_conformant,
    sandbox,
    wheel_files,
)
from typer.testing import CliRunner

from citefinder.cli import app
from citefinder.host import HOST

runner = CliRunner()

SOURCE = "skills/use-citefinder/SKILL.md"
STUB_REL = Path(".claude/skills/use-citefinder/SKILL.md")
# The stamp every release before the pkgskills adoption wrote.
OLD_STAMP = (
    "<!-- generated by citefinder 0.4.4 (mode=local); do not edit — "
    "run: uv run citefinder install --local --force -->"
)


@pytest.fixture
def box(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Sandbox:
    return sandbox(tmp_path, monkeypatch)


def _front() -> str:
    front, _ = split_frontmatter(HOST.read(SOURCE))
    assert front is not None
    return front.raw


# --- declaration and package data -------------------------------------------


def test_skill_follows_the_agent_skills_spec() -> None:
    assert_spec_conformant(HOST)


def test_prompts_name_only_real_commands() -> None:
    assert_prompt_commands(HOST, app)


def test_body_is_loadable_as_package_data() -> None:
    resource = resources.files("citefinder.prompts").joinpath(SOURCE)
    assert resource.is_file()
    assert HOST.read(SOURCE) == resource.read_text(encoding="utf-8")


def test_built_wheel_ships_the_skill_tree(tmp_path: Path) -> None:
    """Guards the hatchling include.

    An editable install resolves `citefinder.prompts` straight to the repo, so
    it would keep working even if the build stopped shipping the prompts — and
    `skill` would then fail only for people who installed from PyPI.
    """
    names = wheel_files(Path(__file__).resolve().parent.parent, tmp_path)
    expected = [SOURCE, *(doc.source for doc in HOST.docs)]
    for source in expected:
        assert f"citefinder/prompts/{source}" in names


# --- skill and doc -----------------------------------------------------------


def test_skill_prints_without_a_stub_installed(box: Sandbox) -> None:
    result = runner.invoke(app, ["skill"])
    assert result.exit_code == 0, result.output
    assert not (box.repo / ".claude").exists()
    assert result.stdout == render_prompt(HOST.read(SOURCE), "citefinder")


def test_bare_skill_and_named_skill_print_the_same_body(box: Sandbox) -> None:
    bare = runner.invoke(app, ["skill"])
    named = runner.invoke(app, ["skill", "use-citefinder"])
    assert bare.exit_code == named.exit_code == 0
    assert bare.stdout == named.stdout
    assert "{cli}" not in bare.stdout


@pytest.mark.parametrize("doc", HOST.docs, ids=lambda d: d.name)
def test_doc_renders_the_cli_for_the_installed_mode(box: Sandbox, doc) -> None:
    unrendered = HOST.read(doc.source)
    result = runner.invoke(app, ["doc", doc.name])
    assert result.exit_code == 0, result.output
    assert result.stdout == render_prompt(unrendered, "citefinder")

    assert runner.invoke(app, ["install", "--local"]).exit_code == 0
    result = runner.invoke(app, ["doc", doc.name])
    assert result.stdout == render_prompt(unrendered, "uv run citefinder")


# --- install -----------------------------------------------------------------


def test_install_local_carries_the_frontmatter_verbatim(box: Sandbox) -> None:
    result = runner.invoke(app, ["install", "--local"])
    assert result.exit_code == 0, result.output
    text = (box.repo / STUB_REL).read_text(encoding="utf-8")
    assert text.startswith(_front())
    assert "uv run citefinder skill use-citefinder" in text
    assert not (box.home / STUB_REL).exists()

    check = runner.invoke(app, ["install", "--local", "--check"])
    assert check.exit_code == 0, check.output
    assert "ok" in check.stdout


def test_install_defaults_to_global(box: Sandbox) -> None:
    assert runner.invoke(app, ["install"]).exit_code == 0
    assert (box.home / STUB_REL).is_file()
    assert not (box.repo / STUB_REL).exists()
    assert runner.invoke(app, ["install", "--check"]).exit_code == 0


def test_install_local_from_a_subdirectory_targets_the_repo_root(
    box: Sandbox, monkeypatch: pytest.MonkeyPatch
) -> None:
    sub = box.repo / "paper" / "sections"
    sub.mkdir(parents=True)
    monkeypatch.chdir(sub)
    assert runner.invoke(app, ["install", "--local"]).exit_code == 0
    assert (box.repo / STUB_REL).is_file()


def test_check_with_nothing_installed_fails(box: Sandbox) -> None:
    result = runner.invoke(app, ["install", "--check"])
    assert result.exit_code != 0
    assert not (box.home / ".claude").exists()
    assert not (box.repo / ".claude").exists()


def test_pre_adoption_stub_is_foreign_until_forced(box: Sandbox) -> None:
    path = box.repo / STUB_REL
    path.parent.mkdir(parents=True)
    old = f"{_front()}\n{OLD_STAMP}\n\n# use-citefinder\n"
    path.write_text(old, encoding="utf-8")

    check = runner.invoke(app, ["install", "--local", "--check"])
    assert check.exit_code != 0
    assert "foreign" in check.output

    refused = runner.invoke(app, ["install", "--local"])
    assert refused.exit_code != 0
    assert path.read_text(encoding="utf-8") == old

    assert runner.invoke(app, ["install", "--local", "--force"]).exit_code == 0
    assert runner.invoke(app, ["install", "--local", "--check"]).exit_code == 0


def test_hand_authored_skill_is_refused_without_force(box: Sandbox) -> None:
    path = box.repo / STUB_REL
    path.parent.mkdir(parents=True)
    path.write_text("# my own use-citefinder skill\n", encoding="utf-8")

    assert runner.invoke(app, ["install", "--local"]).exit_code != 0
    assert path.read_text(encoding="utf-8") == "# my own use-citefinder skill\n"
    assert runner.invoke(app, ["install", "--local", "--force"]).exit_code == 0
    assert path.read_text(encoding="utf-8").startswith(_front())


def test_install_never_writes_through_a_symlink(box: Sandbox) -> None:
    target = box.repo / "elsewhere.md"
    target.write_text("keep me\n", encoding="utf-8")
    path = box.repo / STUB_REL
    path.parent.mkdir(parents=True)
    path.symlink_to(target)

    assert runner.invoke(app, ["install", "--local"]).exit_code != 0
    assert runner.invoke(app, ["install", "--local", "--force"]).exit_code == 0
    assert target.read_text(encoding="utf-8") == "keep me\n"
    assert not path.is_symlink()


def test_global_copy_wins_over_a_stale_local_one(box: Sandbox) -> None:
    local = box.repo / STUB_REL
    local.parent.mkdir(parents=True)
    local.write_text(f"{_front()}\n{OLD_STAMP}\n", encoding="utf-8")
    assert runner.invoke(app, ["install"]).exit_code == 0

    # With both present, printing follows the global copy's mode.
    result = runner.invoke(app, ["doc", "use-citefinder/openalex"])
    assert "citefinder doi" in result.stdout
    assert "uv run citefinder" not in result.stdout

    # A bare check still judges every mode: the shadowed local stub is named,
    # and its foreign status fails the check until it is repaired.
    check = runner.invoke(app, ["install", "--check"])
    assert check.exit_code != 0
    assert "shadows the per-repo stub" in check.output
    assert runner.invoke(app, ["install", "--local", "--force"]).exit_code == 0
    assert runner.invoke(app, ["install", "--check"]).exit_code == 0


def test_bootstrap_check_runs_through_uv_in_every_mode(box: Sandbox) -> None:
    # The check follows `uv add citefinder`, so only `uv run` is sure to resolve,
    # even when a global stub renders the other commands as bare `citefinder`.
    result = runner.invoke(app, ["skill"])
    assert "uv run citefinder --help" in result.stdout
