"""Materialize the `use-citefinder` dispatcher stub into a `.claude/` tree.

Mirrors [planners](https://github.com/gitronald/planners): the package is the
source of truth and `.claude/` holds only a thin, generated, version-stamped
stub. The skill body ships as package data at `citefinder/prompts/skill.md` and
never leaves it — `citefinder skill` prints it on demand, and the stub tells the
agent to run that. So the instructions live in exactly one place, and a
consuming repo cannot end up with a stale copy of them: there is no copy.

What the stub does carry is the frontmatter — `name` and the `description`
triggers, which Claude Code has to read off disk to know when to fire the skill.
That is lifted verbatim from the bundled body, so the trigger text has a single
source too.

Two install **modes**, both first-class:

* **global** (default) — the CLI is on `PATH` (`uv tool install citefinder`);
  one stub at `~/.claude/skills/use-citefinder/` serves every repo.
* **local** (`--local`) — the stub is vendored per repo at
  `<repo>/.claude/skills/use-citefinder/`, e.g. so it ships with the checkout.

A file's mode is the one its location implies — under `$HOME` it is global,
under a repo it is local — so `--check` needs no flag to know how a copy should
read, and a stub carried to the other location reads as drifted rather than
validating against how it was once rendered. The stamp records the version and
mode for provenance; a file without the stamp line is recognizable as
hand-authored and never clobbered without `--force`.
"""

from __future__ import annotations

import re
from importlib import resources
from pathlib import Path
from typing import Literal, cast

Mode = Literal["local", "global"]

# Path of the generated skill relative to its mode base ($HOME for global, the
# repo root for local). Identical in both modes, so the two never collide.
SKILL_REL = Path(".claude/skills/use-citefinder/SKILL.md")

_PROMPTS_PACKAGE = "citefinder.prompts"
_SKILL_RESOURCE = "skill.md"

# Sentinel every generated copy carries. Used to tell our own artifact apart
# from a hand-authored skill at the same path — never overwrite a file that
# lacks it without `--force`.
GENERATED_MARKER = "generated by citefinder"

_STAMP_PREFIX = f"<!-- {GENERATED_MARKER} "

# The stamp is recognized only as a whole line at line start — a hand-authored
# file that merely *mentions* the marker phrase in prose (say, quoting the
# README's stamp example) must not read as ours.
_STAMP_LINE_RE = re.compile(rf"(?m)^{re.escape(_STAMP_PREFIX)}")

# The version token inside the stamp, masked out of the drift comparison: a
# routine release changes only this token, and flagging every upgrade as drift
# would train users to ignore `--check`.
_STAMP_VERSION_RE = re.compile(rf"(?m)^({re.escape(_STAMP_PREFIX)})\S+")

_FRONTMATTER_FENCE = "---\n"


def invocation(mode: Mode) -> str:
    """The command prefix the generated stub uses to call this CLI.

    The single source for this string: the stub's `skill` and `install --check`
    commands both route through it, so the prefix is never written twice.
    """
    return "citefinder" if mode == "global" else "uv run citefinder"


def install_command(mode: Mode, *, force: bool = False) -> str:
    """The command that materializes the stub for `mode`.

    Mode-correct on purpose: pointing a per-repo install at the bare global
    command would write to `~/.claude/` and leave the repo's stub just as stale
    as before.
    """
    parts = [invocation(mode), "install"]
    if mode == "local":
        parts.append("--local")
    if force:
        parts.append("--force")
    return " ".join(parts)


def skill_command(mode: Mode) -> str:
    """The command that prints the full skill body for `mode`."""
    return f"{invocation(mode)} skill"


def check_command(mode: Mode) -> str:
    """The command that drift-checks `mode`'s stub.

    Carries `--local` for a local stub — bare `--check` prefers the global
    copy, so a repo stub naming the bare command could end up reporting on a
    different file than the one the reader is looking at.
    """
    return f"{install_command(mode)} --check"


def repair_command(mode: Mode) -> str:
    """The `--force` install, baked into the stamp so a file names its own fix."""
    return install_command(mode, force=True)


def _stamp(version: str, mode: Mode) -> str:
    """The generated-by comment the installed skill carries after frontmatter.

    An HTML comment — invisible in rendered markdown — recording the version
    and mode for provenance. Drift is judged on content, with the version
    token masked, so the stamp alone never flags a routine upgrade.
    """
    return (
        f"<!-- generated by citefinder {version} (mode={mode}); "
        f"do not edit — run: {repair_command(mode)} -->"
    )


def load_body() -> str:
    """The bundled skill body, verbatim (frontmatter included)."""
    return (
        resources.files(_PROMPTS_PACKAGE)
        .joinpath(_SKILL_RESOURCE)
        .read_text(encoding="utf-8")
    )


def split_frontmatter(text: str) -> tuple[str, str]:
    """Split markdown into its leading YAML frontmatter block and the rest.

    The frontmatter is returned *including* both `---` fences and its trailing
    newline, so `front + body` reconstructs the input exactly — the stamp is
    spliced between the two halves and the skill's `name`/`description`
    triggers survive byte-for-byte. Returns `("", text)` when there is no
    frontmatter.
    """
    if not text.startswith(_FRONTMATTER_FENCE):
        return "", text
    end = text.find("\n" + _FRONTMATTER_FENCE, len(_FRONTMATTER_FENCE) - 1)
    if end == -1:
        return "", text
    split_at = end + len(_FRONTMATTER_FENCE) + 1
    return text[:split_at], text[split_at:]


def skill_body() -> str:
    """The skill instructions, frontmatter stripped — what `citefinder skill` prints.

    The frontmatter is Claude Code's trigger metadata, not instructions; an
    agent that has already loaded the stub and run this command does not need
    it repeated.
    """
    _, body = split_frontmatter(load_body())
    return body.strip() + "\n"


def _frontmatter(version: str) -> str:
    """The bundled body's frontmatter, verbatim — the stub's trigger metadata.

    Lifted rather than restated so `name` and the `description` triggers have a
    single source. `version` only appears in the error, to name what to fix.
    """
    front, _ = split_frontmatter(load_body())
    if not front:
        raise ValueError(
            f"bundled {_SKILL_RESOURCE} is missing its YAML frontmatter; "
            f"citefinder {version} cannot render a stub without name/description"
        )
    return front


def render_stub(version: str, mode: Mode = "global") -> str:
    """The generated dispatcher stub for `mode`.

    Pure transform — the bytes this returns are exactly what gets written and
    exactly what drift is checked against. Deliberately short: everything a
    reader needs beyond the triggers is fetched with one command, so this file
    has almost no surface on which to go stale.
    """
    return f"""\
{_frontmatter(version)}
{_stamp(version, mode)}

# use-citefinder

Reference-lookup guidance for `citefinder` — Crossref and OpenAlex DOI lookup,
bibliographic search, and `.bib` verification. This file is a generated stub,
not the source of truth: the instructions live inside the installed package and
are printed on demand, so they always match the version you have.

**Load the full instructions and follow them:**

```bash
{skill_command(mode)}
```

If that command is not found, citefinder is not installed in this environment —
`uv add citefinder` (or `uv tool install citefinder`) first.

**If this stub looks out of date**, check it against the installed package:

```bash
{check_command(mode)}
```

`drifted` or `missing` means this stub predates the installed CLI. Re-materialize
it with `{install_command(mode, force=True)}`, then start a fresh context.
"""


def skill_path(root: Path, mode: Mode) -> Path:
    """Where the generated skill lives for `mode`: under `$HOME` or the repo."""
    base = Path.home() if mode == "global" else root
    return base / SKILL_REL


def find_repo_root(start: Path | None = None) -> Path:
    """Walk up from `start` (default: cwd) to the nearest directory that looks
    like a repo root — one containing `.git` or a `.claude/` tree.

    A local install must target the root Claude Code actually loads skills
    from at startup, not whatever subdirectory the command was run from.
    Falls back to `start` itself when no marker is found.
    """
    base = (start or Path.cwd()).resolve()
    for candidate in (base, *base.parents):
        if (candidate / ".git").exists() or (candidate / ".claude").is_dir():
            return candidate
    return base


def write_skill(root: Path, version: str, mode: Mode = "global") -> Path:
    """Write the generated skill for `mode`, creating parent dirs as needed.

    A symlink at the target path — dangling or not — is replaced with a plain
    file, never written through: the write must not be able to reach a target
    outside the `.claude/` tree it was aimed at.
    """
    path = skill_path(root, mode)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        path.unlink()
    path.write_text(render_stub(version, mode), encoding="utf-8")
    return path


def _read_plain(path: Path) -> str | None:
    """The file's text, or `None` for anything that is not a readable plain
    file — a symlink (dangling included), a directory, unreadable or
    undecodable bytes. Never raises; callers treat `None` as "not ours"."""
    if path.is_symlink() or not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def is_generated(path: Path) -> bool:
    """True only for a real, plain file *we* generated.

    The overwrite guard: it must be a regular file (not a directory or a
    symlink) carrying the stamp *line* — a hand-authored skill that merely
    mentions :data:`GENERATED_MARKER` in prose is never silently replaced.
    """
    text = _read_plain(path)
    return text is not None and _STAMP_LINE_RE.search(text) is not None


def resolve_installed(root: Path) -> tuple[Path, Mode] | None:
    """Find an installed skill, preferring global over local.

    Returns `(path, mode)` with the *location-implied* mode — the mode that
    determines how a stub at that path must be invoked — or `None` when
    neither location is occupied. A dangling symlink counts as occupied:
    something is squatting at the path even though `exists()` follows the
    link and says otherwise. Global wins when both exist because that is
    Claude Code's own precedence — a repo that has switched to global reads
    as global even if a stale per-repo copy lingers.
    """
    for mode in ("global", "local"):
        path = skill_path(root, cast("Mode", mode))
        if path.is_symlink() or path.exists():
            return path, cast("Mode", mode)
    return None


def _mask_stamp_version(text: str) -> str:
    """The text with the stamp's version token replaced by `*`."""
    return _STAMP_VERSION_RE.sub(r"\g<1>*", text)


def check_mode(
    root: Path, version: str, mode: Mode
) -> Literal["ok", "drifted", "missing"]:
    """Drift for a *specific* mode's location.

    The comparison masks the stamped version, so `drifted` means the rendered
    *content* — frontmatter triggers or the stub template — no longer matches
    this version's render; a routine upgrade alone never flags. Anything at
    the path that is not a readable plain file — a directory, a symlink
    (dangling included), undecodable bytes — reads as `drifted` (something
    foreign is squatting there) rather than raising.
    """
    path = skill_path(root, mode)
    if not path.is_symlink() and not path.exists():
        return "missing"
    text = _read_plain(path)
    if text is None:
        return "drifted"
    rendered = render_stub(version, mode)
    if _mask_stamp_version(text) == _mask_stamp_version(rendered):
        return "ok"
    return "drifted"


def check(root: Path, version: str) -> Literal["ok", "drifted", "missing"]:
    """Drift for whichever skill is installed, judged by its location.

    Resolves the installed copy (global first) and compares it against a
    re-render for *where it sits*, so a local-rendered stub carried to the
    global path reads as `drifted`: its embedded `uv run` commands are wrong
    for global use no matter how it was originally rendered. An unstamped or
    hand-authored file likewise reads as `drifted` — it is not something this
    package generated. The CLI's `install --check` does this same resolution
    itself, because it also reports the path it judged; this is the one-call
    form for library use.
    """
    found = resolve_installed(root)
    if found is None:
        return "missing"
    _, mode = found
    return check_mode(root, version, mode)
