"""Materialize the bundled `use-citefinder` skill into a `.claude/` tree.

The package is the source of truth: the canonical skill body ships as package
data at `citefinder/prompts/skill.md`, and `install` writes a thin,
version-stamped copy to `.claude/skills/use-citefinder/SKILL.md`. Consumers
that hand-copied the skill could drift silently from the version they had
installed; a generated artifact plus `install --check` makes that drift
visible.

Two install **modes**, both first-class:

* **global** (default) — the CLI is on `PATH` (`uv tool install citefinder`);
  one copy at `~/.claude/skills/use-citefinder/` serves every repo.
* **local** (`--local`) — the skill is vendored per repo at
  `<repo>/.claude/skills/use-citefinder/`, e.g. so it ships with the checkout.

The resolved mode is stamped into the generated file, so `--check` recovers it
without the flag being re-passed, and an unstamped file at the target path is
recognizable as hand-authored and never clobbered without `--force`.

Unlike planners — the package this pattern mirrors — there is a single skill
body rather than seven lifecycle bodies behind a dispatcher, so the holder and
the body collapse into one file: the generated artifact *is* the full skill.
"""

from __future__ import annotations

import re
from importlib import resources
from pathlib import Path
from typing import Literal, cast

Mode = Literal["local", "global"]

# Path of the generated skill relative to its mode base ($HOME for global, the
# repo root for local). Identical in both modes, so the two never collide.
SKILL_REL = Path(".claude/skills/use-citefinder/SKILL.md")

_PROMPTS_PACKAGE = "citefinder.prompts"
_SKILL_RESOURCE = "skill.md"

# The mode recorded in the generated stamp, so `check` can recover it from the
# file alone rather than requiring the caller to re-state it.
_MODE_STAMP_RE = re.compile(r"\(mode=(local|global)\)")

# Sentinel every generated copy carries. Used to tell our own artifact apart
# from a hand-authored skill at the same path — never overwrite a file that
# lacks it without `--force`.
GENERATED_MARKER = "generated by citefinder"

_FRONTMATTER_FENCE = "---\n"


def install_command(mode: Mode, *, force: bool = False) -> str:
    """The command that materializes the skill for `mode`.

    Mode-correct on purpose: pointing a per-repo install at the bare global
    command would write to `~/.claude/` and leave the repo copy just as stale
    as before.
    """
    parts = ["citefinder" if mode == "global" else "uv run citefinder", "install"]
    if mode == "local":
        parts.append("--local")
    if force:
        parts.append("--force")
    return " ".join(parts)


def repair_command(mode: Mode) -> str:
    """The `--force` install, baked into the stamp so a file names its own fix."""
    return install_command(mode, force=True)


def _stamp(version: str, mode: Mode) -> str:
    """The generated-by comment the installed skill carries after frontmatter.

    An HTML comment — invisible in rendered markdown, parseable by
    :func:`_recover_mode` — carrying the version (the drift signal) and the
    resolved mode.
    """
    return (
        f"<!-- generated by citefinder {version} (mode={mode}); "
        f"do not edit — run: {repair_command(mode)} -->"
    )


def load_body() -> str:
    """The bundled skill body, verbatim (frontmatter included)."""
    return (
        resources.files(_PROMPTS_PACKAGE)
        .joinpath(_SKILL_RESOURCE)
        .read_text(encoding="utf-8")
    )


def split_frontmatter(text: str) -> tuple[str, str]:
    """Split markdown into its leading YAML frontmatter block and the rest.

    The frontmatter is returned *including* both `---` fences and its trailing
    newline, so `front + body` reconstructs the input exactly — the stamp is
    spliced between the two halves and the skill's `name`/`description`
    triggers survive byte-for-byte. Returns `("", text)` when there is no
    frontmatter.
    """
    if not text.startswith(_FRONTMATTER_FENCE):
        return "", text
    end = text.find("\n" + _FRONTMATTER_FENCE, len(_FRONTMATTER_FENCE) - 1)
    if end == -1:
        return "", text
    split_at = end + len(_FRONTMATTER_FENCE) + 1
    return text[:split_at], text[split_at:]


def render(version: str, mode: Mode = "global") -> str:
    """The full generated artifact: bundled body with a stamp after frontmatter.

    Pure transform — the bytes this returns are exactly what gets written and
    exactly what drift is checked against.
    """
    front, body = split_frontmatter(load_body())
    if not front:
        raise ValueError(
            f"bundled {_SKILL_RESOURCE} is missing its YAML frontmatter; "
            "the skill cannot be installed without name/description triggers"
        )
    body = body.lstrip("\n")
    return f"{front}\n{_stamp(version, mode)}\n\n{body}"


def skill_path(root: Path, mode: Mode) -> Path:
    """Where the generated skill lives for `mode`: under `$HOME` or the repo."""
    base = Path.home() if mode == "global" else root
    return base / SKILL_REL


def write_skill(root: Path, version: str, mode: Mode = "global") -> Path:
    """Write the generated skill for `mode`, creating parent dirs as needed."""
    path = skill_path(root, mode)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(version, mode), encoding="utf-8")
    return path


def is_generated(path: Path) -> bool:
    """True only for a real, plain file *we* generated.

    The overwrite guard: it must be a regular file (not a directory), not a
    symlink (so a write can never traverse a link out to an unrelated target),
    and must carry :data:`GENERATED_MARKER` — so a hand-authored skill that
    merely happens to sit at the target path is never silently replaced.
    """
    if path.is_symlink() or not path.is_file():
        return False
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False


def _recover_mode(text: str) -> Mode | None:
    """Recover the mode stamped into an installed skill, or `None` if unstamped."""
    match = _MODE_STAMP_RE.search(text)
    return cast("Mode", match.group(1)) if match else None


def resolve_installed(root: Path) -> tuple[Path, Mode] | None:
    """Find an installed skill, preferring global over local.

    Returns `(path, mode)` with the *location-implied* mode, or `None` when
    neither location has one. Global wins when both exist because that is
    Claude Code's own precedence — a repo that has switched to global reads as
    global even if a stale per-repo copy lingers.
    """
    for mode in ("global", "local"):
        path = skill_path(root, cast("Mode", mode))
        if path.exists():
            return path, cast("Mode", mode)
    return None


def resolve_mode(root: Path) -> Mode:
    """The installed skill's authoritative mode, or `global` when none exists.

    The stamp inside the file wins over the location it was found at (a stamped
    copy survives being moved), falling back to the location-implied mode for
    an unstamped or unreadable one. Callers that only need the mode — to name
    the right repair command, say — use this so they agree with :func:`check`.
    """
    found = resolve_installed(root)
    if found is None:
        return "global"
    path, location_mode = found
    if path.is_symlink() or not path.is_file():
        return location_mode
    try:
        return _recover_mode(path.read_text(encoding="utf-8")) or location_mode
    except (OSError, UnicodeDecodeError):
        return location_mode


def check_mode(
    root: Path, version: str, mode: Mode
) -> Literal["ok", "drifted", "missing"]:
    """Drift for a *specific* mode's location.

    Anything at the path that is not a readable plain file — a directory, a
    symlink, undecodable bytes — reads as `drifted` (something foreign is
    squatting there) rather than raising.
    """
    path = skill_path(root, mode)
    if not path.exists():
        return "missing"
    if path.is_symlink() or not path.is_file():
        return "drifted"
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return "drifted"
    return "ok" if text == render(version, mode) else "drifted"


def check(root: Path, version: str) -> Literal["ok", "drifted", "missing"]:
    """Drift for whichever skill is installed, in whatever mode.

    Resolves the installed copy (global first), recovers its stamped mode, and
    compares against a re-render in that mode — so `install --check` is a
    single no-arg command that "just knows" the mode. An unstamped file falls
    back to the location-implied mode and will read as `drifted`, which is the
    right answer: it is not something this package generated.
    """
    found = resolve_installed(root)
    if found is None:
        return "missing"
    path, location_mode = found
    if path.is_symlink() or not path.is_file():
        return "drifted"
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return "drifted"
    mode = _recover_mode(text) or location_mode
    return "ok" if text == render(version, mode) else "drifted"
