"""Materialize the `use-citefinder` dispatcher stub into a `.claude/` tree.

Mirrors [planners](https://github.com/gitronald/planners): the package is the
source of truth and `.claude/` holds only a thin, generated, version-stamped
stub. The skill body ships as package data at `citefinder/prompts/skill.md` and
never leaves it — `citefinder skill` prints it on demand, and the stub tells the
agent to run that. So the instructions live in exactly one place, and a
consuming repo cannot end up with a stale copy of them: there is no copy.

What the stub does carry is the frontmatter — `name` and the `description`
triggers, which Claude Code has to read off disk to know when to fire the skill.
That is lifted verbatim from the bundled body, so the trigger text has a single
source too.

Two install **modes**, both first-class:

* **global** (default) — the CLI is on `PATH` (`uv tool install citefinder`);
  one stub at `~/.claude/skills/use-citefinder/` serves every repo.
* **local** (`--local`) — the stub is vendored per repo at
  `<repo>/.claude/skills/use-citefinder/`, e.g. so it ships with the checkout.

The resolved mode is stamped into the stub, so `--check` recovers it without the
flag being re-passed and the stub's own commands are invocable as written. An
unstamped file at the target path is recognizable as hand-authored and never
clobbered without `--force`.
"""

from __future__ import annotations

import re
from importlib import resources
from pathlib import Path
from typing import Literal, cast

Mode = Literal["local", "global"]

# Path of the generated skill relative to its mode base ($HOME for global, the
# repo root for local). Identical in both modes, so the two never collide.
SKILL_REL = Path(".claude/skills/use-citefinder/SKILL.md")

_PROMPTS_PACKAGE = "citefinder.prompts"
_SKILL_RESOURCE = "skill.md"

# The mode recorded in the generated stamp, so `check` can recover it from the
# file alone rather than requiring the caller to re-state it.
_MODE_STAMP_RE = re.compile(r"\(mode=(local|global)\)")

# Sentinel every generated copy carries. Used to tell our own artifact apart
# from a hand-authored skill at the same path — never overwrite a file that
# lacks it without `--force`.
GENERATED_MARKER = "generated by citefinder"

_FRONTMATTER_FENCE = "---\n"


def invocation(mode: Mode) -> str:
    """The command prefix the generated stub uses to call this CLI.

    The single source for this string: the stub's `skill` and `install --check`
    commands both route through it, so the prefix is never written twice.
    """
    return "citefinder" if mode == "global" else "uv run citefinder"


def install_command(mode: Mode, *, force: bool = False) -> str:
    """The command that materializes the stub for `mode`.

    Mode-correct on purpose: pointing a per-repo install at the bare global
    command would write to `~/.claude/` and leave the repo's stub just as stale
    as before.
    """
    parts = [invocation(mode), "install"]
    if mode == "local":
        parts.append("--local")
    if force:
        parts.append("--force")
    return " ".join(parts)


def skill_command(mode: Mode) -> str:
    """The command that prints the full skill body for `mode`."""
    return f"{invocation(mode)} skill"


def repair_command(mode: Mode) -> str:
    """The `--force` install, baked into the stamp so a file names its own fix."""
    return install_command(mode, force=True)


def _stamp(version: str, mode: Mode) -> str:
    """The generated-by comment the installed skill carries after frontmatter.

    An HTML comment — invisible in rendered markdown, parseable by
    :func:`_recover_mode` — carrying the version (the drift signal) and the
    resolved mode.
    """
    return (
        f"<!-- generated by citefinder {version} (mode={mode}); "
        f"do not edit — run: {repair_command(mode)} -->"
    )


def load_body() -> str:
    """The bundled skill body, verbatim (frontmatter included)."""
    return (
        resources.files(_PROMPTS_PACKAGE)
        .joinpath(_SKILL_RESOURCE)
        .read_text(encoding="utf-8")
    )


def split_frontmatter(text: str) -> tuple[str, str]:
    """Split markdown into its leading YAML frontmatter block and the rest.

    The frontmatter is returned *including* both `---` fences and its trailing
    newline, so `front + body` reconstructs the input exactly — the stamp is
    spliced between the two halves and the skill's `name`/`description`
    triggers survive byte-for-byte. Returns `("", text)` when there is no
    frontmatter.
    """
    if not text.startswith(_FRONTMATTER_FENCE):
        return "", text
    end = text.find("\n" + _FRONTMATTER_FENCE, len(_FRONTMATTER_FENCE) - 1)
    if end == -1:
        return "", text
    split_at = end + len(_FRONTMATTER_FENCE) + 1
    return text[:split_at], text[split_at:]


def skill_body() -> str:
    """The skill instructions, frontmatter stripped — what `citefinder skill` prints.

    The frontmatter is Claude Code's trigger metadata, not instructions; an
    agent that has already loaded the stub and run this command does not need
    it repeated.
    """
    _, body = split_frontmatter(load_body())
    return body.strip() + "\n"


def _frontmatter(version: str) -> str:
    """The bundled body's frontmatter, verbatim — the stub's trigger metadata.

    Lifted rather than restated so `name` and the `description` triggers have a
    single source. `version` only appears in the error, to name what to fix.
    """
    front, _ = split_frontmatter(load_body())
    if not front:
        raise ValueError(
            f"bundled {_SKILL_RESOURCE} is missing its YAML frontmatter; "
            f"citefinder {version} cannot render a stub without name/description"
        )
    return front


def render_stub(version: str, mode: Mode = "global") -> str:
    """The generated dispatcher stub for `mode`.

    Pure transform — the bytes this returns are exactly what gets written and
    exactly what drift is checked against. Deliberately short: everything a
    reader needs beyond the triggers is fetched with one command, so this file
    has almost no surface on which to go stale.
    """
    inv = invocation(mode)
    return f"""\
{_frontmatter(version)}
{_stamp(version, mode)}

# use-citefinder

Reference-lookup guidance for `citefinder` — Crossref and OpenAlex DOI lookup,
bibliographic search, and `.bib` verification. This file is a generated stub,
not the source of truth: the instructions live inside the installed package and
are printed on demand, so they always match the version you have.

**Load the full instructions and follow them:**

```bash
{inv} skill
```

If that command is not found, citefinder is not installed in this environment —
`uv add citefinder` (or `uv tool install citefinder`) first.

**If this stub looks out of date**, check it against the installed package:

```bash
{inv} install --check
```

`drifted` or `missing` means this stub predates the installed CLI. Re-materialize
it with `{install_command(mode, force=True)}`, then start a fresh context.
"""


def skill_path(root: Path, mode: Mode) -> Path:
    """Where the generated skill lives for `mode`: under `$HOME` or the repo."""
    base = Path.home() if mode == "global" else root
    return base / SKILL_REL


def write_skill(root: Path, version: str, mode: Mode = "global") -> Path:
    """Write the generated skill for `mode`, creating parent dirs as needed."""
    path = skill_path(root, mode)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_stub(version, mode), encoding="utf-8")
    return path


def is_generated(path: Path) -> bool:
    """True only for a real, plain file *we* generated.

    The overwrite guard: it must be a regular file (not a directory), not a
    symlink (so a write can never traverse a link out to an unrelated target),
    and must carry :data:`GENERATED_MARKER` — so a hand-authored skill that
    merely happens to sit at the target path is never silently replaced.
    """
    if path.is_symlink() or not path.is_file():
        return False
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False


def _recover_mode(text: str) -> Mode | None:
    """Recover the mode stamped into an installed skill, or `None` if unstamped."""
    match = _MODE_STAMP_RE.search(text)
    return cast("Mode", match.group(1)) if match else None


def resolve_installed(root: Path) -> tuple[Path, Mode] | None:
    """Find an installed skill, preferring global over local.

    Returns `(path, mode)` with the *location-implied* mode, or `None` when
    neither location has one. Global wins when both exist because that is
    Claude Code's own precedence — a repo that has switched to global reads as
    global even if a stale per-repo copy lingers.
    """
    for mode in ("global", "local"):
        path = skill_path(root, cast("Mode", mode))
        if path.exists():
            return path, cast("Mode", mode)
    return None


def resolve_mode(root: Path) -> Mode:
    """The installed skill's authoritative mode, or `global` when none exists.

    The stamp inside the file wins over the location it was found at (a stamped
    copy survives being moved), falling back to the location-implied mode for
    an unstamped or unreadable one. Callers that only need the mode — to name
    the right repair command, say — use this so they agree with :func:`check`.
    """
    found = resolve_installed(root)
    if found is None:
        return "global"
    path, location_mode = found
    if path.is_symlink() or not path.is_file():
        return location_mode
    try:
        return _recover_mode(path.read_text(encoding="utf-8")) or location_mode
    except (OSError, UnicodeDecodeError):
        return location_mode


def check_mode(
    root: Path, version: str, mode: Mode
) -> Literal["ok", "drifted", "missing"]:
    """Drift for a *specific* mode's location.

    Anything at the path that is not a readable plain file — a directory, a
    symlink, undecodable bytes — reads as `drifted` (something foreign is
    squatting there) rather than raising.
    """
    path = skill_path(root, mode)
    if not path.exists():
        return "missing"
    if path.is_symlink() or not path.is_file():
        return "drifted"
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return "drifted"
    return "ok" if text == render_stub(version, mode) else "drifted"


def check(root: Path, version: str) -> Literal["ok", "drifted", "missing"]:
    """Drift for whichever skill is installed, in whatever mode.

    Resolves the installed copy (global first), recovers its stamped mode, and
    compares against a re-render in that mode — so `install --check` is a
    single no-arg command that "just knows" the mode. An unstamped file falls
    back to the location-implied mode and will read as `drifted`, which is the
    right answer: it is not something this package generated.
    """
    found = resolve_installed(root)
    if found is None:
        return "missing"
    path, location_mode = found
    if path.is_symlink() or not path.is_file():
        return "drifted"
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return "drifted"
    mode = _recover_mode(text) or location_mode
    return "ok" if text == render_stub(version, mode) else "drifted"
